### ISSUE TITLE
High cpu load when navigating to .doc or .ppt files

### ISSUE THREAD

**Issue by tullo** [marsbard/docker-alfresco#1]
Navigation to any of the .doc or .ppt files in site/swsdp/documentlibrary triggers the generation of the webpreviev transformation and keeps all 8 cores busy at +35% load for nearly 5 minutes. Not sure what to look for.

How to reproduce that kind of load on your box?
1. grua stack
2.  [https://localhost/share/page/site/swsdp/documentlibrary](https://localhost/share/page/site/swsdp/documentlibrary)
3. Meeting Notes
4. Chose and click on a doc of you liking

**Comment by digcat** [comment]
think this is resolved, please recheck we upgraded libreoffice from memory
